<!DOCTYPE HTML>
<HTML>
	<HEADER>
<title>.:Detector de Plágios.:</title>	
<link rel="stylesheet" href="estiloplagio.css">
	</HEADER>
<body>

<!--------------TITULO------------------------->
<h1 align='center'> Conheça o Detector de Plágios </h1>
<!---------------FIM TITULO-------------------->

<!-----------CENTRAL DE PESQUISA-------------->
<div id='colunacentral'>

<!----------COLUNA MODULO--------------------->
<div id='coluna1'>
<table>

<th>Modulos de<br>Verificação</th>

<tr><td>
<form name='modulos' action=''>    <!---A Definir o formulário de busca----->

<input type='checkbox' name='web'>
Web

</td></tr>

<tr><td>
<input type='checkbox' name='computador'>
Computador

</td></tr>

<tr><td>
<input type='checkbox' name='copia'>
Copia

</td></tr>

<tr><td>
<input type='checkbox' name='arquivo'>
Arquivo

</td></tr>

</form>
</table>

</div>
<!----------FIM COLUNA MODULO--------------------->


<!---------COLUNA INCIDENCIA---------------------->

<div id='coluna2'>
<table>
<tr><th>Incidencia de <br> Palavras</th></td>
<tr><td>[]A decedir</td></tr></tr>
<tr><td>[]A decidir</td></tr>
<tr><td>[]A decidir</td></tr>
</table>
</div>

<!---------COLUNA INCIDENCIA---------------------->

<!---------COLUNA COMPLEXIDADE--------------------->

<div id='coluna3'>
<table>
<tr><th>Complexidade de<br> Pesquisa</th></td>
<tr><td>[]A decedir</td></tr></tr>
<tr><td>[]A decidir</td></tr>
<tr><td>[]A decidir</td></tr>
</table>
</div>

<!---------FIM COLUNA COMPLEXIDADE---------------->

</div>

<!--------FIM CENTRAL DE PESQUISA----------------->

                      <?PHP $texto='Saiba o que Espera este Detector';
                      echo $texto;

//colocar os campos primeiramente, próximo passo

                      ?>
</body>
</html>					